### ISSUE TITLE
Warning: Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by kalko91** [apapacy/realworld-react-universal-hot#1]
Error in console.
_Warning: Did not expect server HTML to contain a div in div._
Will you have idea how to fix this ?
![selection_074](https://user-images.githubusercontent.com/4881079/37976410-24c1c79c-31ea-11e8-9a93-d948420aea94.png)

**Comment by apapacy** [comment]
It seems that plugin webpack.HotModuleReplacementPlugin changes the structure of the document
```
// webpack/config.client.js
  new webpack.HotModuleReplacementPlugin(),
```
if you turn it off, the error disappears

**Comment by kalko91** [comment]
Thanks.
